services:
  taxi_postgres:
    container_name: taxi-database-prod
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taxi}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - taxi_postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - proxy

volumes:
  taxi_postgres_data:

networks:
  proxy:
    external: true
