services:
  taxi_server:
    container_name: taxi-server-${BRANCH}
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - proxy

  taxi_dispatcher:
    container_name: taxi-dispatcher-${BRANCH}
    build:
      context: .
      dockerfile: Dockerfile.spa
      args:
        APP: dispatcher
    networks:
      - proxy

  taxi_driver:
    container_name: taxi-driver-${BRANCH}
    build:
      context: .
      dockerfile: Dockerfile.spa
      args:
        APP: driver
    networks:
      - proxy

  taxi_passenger:
    container_name: taxi-passenger-${BRANCH}
    build:
      context: .
      dockerfile: Dockerfile.spa
      args:
        APP: passenger
    networks:
      - proxy

networks:
  proxy:
    external: true
